class CAdapterSteamBilling002
{
	virtual unknown_ret InitCreditCardPurchase( int32, uint32, bool ) = 0;
	virtual unknown_ret InitPayPalPurchase( int32 ) = 0;
	virtual unknown_ret GetActivationCodeInfo( char const* ) = 0;
	virtual unknown_ret PurchaseWithActivationCode( char const* ) = 0;
	virtual unknown_ret GetFinalPrice() = 0;
	virtual unknown_ret CancelPurchase() = 0;
	virtual unknown_ret CompletePurchase() = 0;
	virtual unknown_ret UpdateCardInfo( uint32 ) = 0;
	virtual unknown_ret DeleteCard( uint32 ) = 0;
	virtual unknown_ret GetCardList() = 0;
	virtual unknown_ret Obsolete_GetLicenses() = 0;
	virtual unknown_ret CancelLicense( int32, int32 ) = 0;
	virtual unknown_ret GetPurchaseReceipts( bool ) = 0;
	virtual unknown_ret SetBillingAddress( uint32, char const*, char const*, char const*, char const*, char const*, char const*, char const*, char const*, char const* ) = 0;
	virtual unknown_ret GetBillingAddress( uint32, char *, char *, char *, char *, char *, char *, char *, char *, char * ) = 0;
	virtual unknown_ret SetShippingAddress( char const*, char const*, char const*, char const*, char const*, char const*, char const*, char const*, char const* ) = 0;
	virtual unknown_ret GetShippingAddress( char *, char *, char *, char *, char *, char *, char *, char *, char * ) = 0;
	virtual unknown_ret SetCardInfo( uint32, int32, char const*, char const*, char const*, char const*, char const*, char const* ) = 0;
	virtual unknown_ret GetCardInfo( uint32, int32 *, char *, char *, char *, char *, char *, char * ) = 0;
	virtual unknown_ret GetLicensePackageID( uint32 ) = 0;
	virtual unknown_ret GetLicenseTimeCreated( uint32 ) = 0;
	virtual unknown_ret GetLicenseTimeNextProcess( uint32 ) = 0;
	virtual unknown_ret GetLicenseMinuteLimit( uint32 ) = 0;
	virtual unknown_ret GetLicenseMinutesUsed( uint32 ) = 0;
	virtual unknown_ret GetLicensePaymentMethod( uint32 ) = 0;
	virtual unknown_ret GetLicenseFlags( uint32 ) = 0;
	virtual unknown_ret GetLicensePurchaseCountryCode( uint32 ) = 0;
	virtual unknown_ret GetReceiptPackageID( uint32 ) = 0;
	virtual unknown_ret GetReceiptStatus( uint32 ) = 0;
	virtual unknown_ret GetReceiptResultDetail( uint32 ) = 0;
	virtual unknown_ret GetReceiptTransTime( uint32 ) = 0;
	virtual unknown_ret GetReceiptTransID( uint32 ) = 0;
	virtual unknown_ret GetReceiptPaymentMethod( uint32 ) = 0;
	virtual unknown_ret GetReceiptBaseCost( uint32 ) = 0;
	virtual unknown_ret GetReceiptTotalDiscount( uint32 ) = 0;
	virtual unknown_ret GetReceiptTax( uint32 ) = 0;
	virtual unknown_ret GetReceiptShipping( uint32 ) = 0;
	virtual unknown_ret GetReceiptCountryCode( uint32 ) = 0;
	virtual unknown_ret GetNumLicenses() = 0;
	virtual unknown_ret GetNumReceipts() = 0;
	virtual unknown_ret PurchaseWithMachineID( int32, char const* ) = 0;
	virtual unknown_ret InitClickAndBuyPurchase( int32, int64, char const*, char const* ) = 0;
	virtual unknown_ret GetPreviousClickAndBuyAccount( int64 *, char *, char * ) = 0;
};

